; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9FCD883D-1A4C-4FD0-B793-6B6662C7D52A}
AppName=Mci-qt
AppVerName=Mci-qt v 0.0.1
AppPublisherURL=https://sourceforge.net/projects/mci
AppSupportURL=https://sourceforge.net/projects/mci
AppUpdatesURL=https://sourceforge.net/projects/mci
DefaultDirName={pf}\McI-qt
DefaultGroupName=Mci-qt
AllowNoIcons=yes
LicenseFile=C:\Documents and Settings\momalley\Desktop\Dev\mci\COPYING
OutputBaseFilename=setup
;SetupIconFile=C:\Documents and Settings\momalley\Desktop\Dev\mci\McIcon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Documents and Settings\momalley\Desktop\Dev\mci\release\mci\McI.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\momalley\Desktop\Dev\mci\release\mci\QtNetwork4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\momalley\Desktop\Dev\mci\release\mci\mingwm10.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\momalley\Desktop\Dev\mci\release\mci\msvcr90.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\momalley\Desktop\Dev\mci\release\mci\QtCore4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Documents and Settings\momalley\Desktop\Dev\mci\release\mci\QtGui4.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Mci-qt"; Filename: "{app}\McI.exe"
Name: "{group}\{cm:UninstallProgram,Mci-qt}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Mci-qt"; Filename: "{app}\McI.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\McI.exe"; Description: "{cm:LaunchProgram,Mci-qt}"; Flags: nowait postinstall skipifsilent

